name: Generar paquete para descarga

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout en Repo
        uses: actions/checkout@v3
      - name: Configurar Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Configurar credenciales de Google Cloud
        run: echo "${{ secrets.GDRIVE_CREDS }}" > google-creds.json
      - name: Instalar Angular CLI
        run: npm i -g @angular/cli
      - name: Instalar dependencias
        run: npm install
      - name: Generar paquete
        run: ng build --aot --base-href /frontend/
      - name: Crear paquete
        id: create_package
        run: tar -zcvf PrePackage.tar.gz ./dist/pastelesfe/
      - name: Instalar gupload
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install gupload
          export PATH=$PATH:~/.local/bin
          
      - name: Subir archivo a Google Drive
        env:
            GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
            gupload --to "$GDRIVE_FOLDER_ID" PrePackage.tar.gz --service-account google-creds.json
        
