name: Generar paquete para descarga

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout en Repo
        uses: actions/checkout@v3
      - name: Configurar Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Instalar Angular CLI
        run: npm i -g @angular/cli
      - name: Instalar dependencias
        run: npm install
      - name: Generar paquete
        run: ng build --aot --base-href /frontend/
      - name: Crear paquete
        id: create_package
        run: tar -zcvf PrePackage.tar.gz ./dist/pastelesfe/
      - name: Subir paquete
        id: upload_package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: PrePackage.tar.gz
      - name: Generar enlace de descarga
        id: download-link
        run: echo "https://github.com/${{ github.repository }}/actions/artifacts/${{ steps.upload_package.outputs.artifact_name }}/PrePackage.tar.gz"
      
        
