name: Generar paquete para descarga

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout en Repo
        uses: actions/checkout@v3
      - name: Configurar Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Instalar Angular CLI
        run: npm i -g @angular/cli
      - name: Instalar dependencias
        run: npm install
      - name: Generar paquete
        run: ng build --aot --base-href /frontend/
      - name: Crear paquete
        id: create_package
        run: tar -zcvf PrePackage.tar.gz ./dist/pastelesfe/
      - name: Instalar gupload
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install gupload
          export PATH=$PATH:~/.local/bin
          echo "${{ secrets.GDRIVE_CREDS }}" >> google-creds.json
          cat google-creds.json
          export GOOGLE_APPLICATION_CREDENTIALS=google-creds.json
      - name: Subir archivo a Google Drive
        run: gupload --to ${{ secrets.GDRIVE_FOLDER_ID }} --file PrePackage.tar.gz PrePackage.tar.gz
        
