name: Deploy to Github Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Configurar Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Instalar Angular CLI
        run: npm i -g @angular/cli
      - name: Instalar dependencias
        run: npm install
      - name: Generar paquete
        run: ng build --aot --base-href /frontend/
      - name: Zippear paquete
        run: tar -zcvf Package.taz.gz ./dist/pastelesfe/
      - name: Subir paquete
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: Package.taz.gz
